ANSIBLE_GROUPS = {
              "node" => ["node"],
              "all_groups:children" => ["node"]
            }

Vagrant.configure(2) do |config|
    config.vm.box = "bento/centos-7.1"
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end
    config.vm.define "node" do |node|
        node.vm.network "private_network", ip: "192.168.33.18"
        node.vm.hostname = "node"
        node.vm.provision "ansible" do |ansible|
            ansible.playbook = "install_fluentd.yml"
            ansible.groups = ANSIBLE_GROUPS
        end
    end
end


